namespace Lara;

/// Contains the SDK version information.
public static class SdkVersion
{
    /// The current version of the Lara .NET SDK.
    /// This constant is auto-generated by the build script.
    /// Manual modifications will be overwritten and may cause unexpected behavior.
    public const string Version = "1.0.0";
} 