name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        framework: [net8.0, net9.0]
        include:
          - framework: net8.0
            dotnet-version: '8.0.x'
          - framework: net9.0
            dotnet-version: '9.0.x'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for SourceLink
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Release --framework ${{ matrix.framework }}
    
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release --framework ${{ matrix.framework }}
      if: matrix.framework == 'net9.0'  # Only run tests on .NET 9 for now
    
    - name: Pack
      run: dotnet pack --no-build --configuration Release --framework ${{ matrix.framework }}
      if: matrix.framework == 'net9.0'  # Only pack on .NET 9
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.framework }}
        path: src/Lara/bin/Release/
        if-no-files-found: error
