name: Publish package to NuGet

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  publish:
    name: Publish package to NuGet
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore src/Lara/Lara.csproj

      - name: Build
        run: dotnet build src/Lara/Lara.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Pack
        run: dotnet pack src/Lara/Lara.csproj --configuration Release --no-build --output nupkgs

      - name: Publish to NuGet
        run: dotnet nuget push nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
